services:
  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "20000:80"
    depends_on:
      - app
    networks:
      - app_net
  db:
    image: postgres:17.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - app_net
  
  redis:
    image: redis:8.0-M04-alpine
    ports:
      - "6379:6379"
    networks:
      - app_net

  app:
    build: .
    env_file:
      - .env
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: fluentd:24224f 
    #     tag: go.gin
    networks:
      - app_net
    depends_on:
      - db
      - fluentd
    restart: always

  elasticsearch:
    image: elasticsearch:8.16.6
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    networks:
      - app_net
  
  kibana:
    image: kibana:8.16.6
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - app_net

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ./logs:/var/log/app
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "24224"]
      interval: 5s
      timeout: 5s
      retries: 10

    

networks:
  app_net: