version: '3'

services:
  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "20000:80"
    networks:
      - app_net

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root  # ✅ Required
      - MYSQL_DATABASE=voting
      - MYSQL_USER=voting
      - MYSQL_PASSWORD=voting
    ports:
      - "3306:3306"
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app_net
  
  app:
    build: .
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless_stopped
    networks:
      - app_net

  
networks:
  app_net: