version: '3'

services:
  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "20000:80"
    networks:
      - app_net
    depends_on:
      - app

  mysql:
    image: mysql:5.7

    environment:
      - MYSQL_ROOT_PASSWORD=root  # ✅ Required
      - MYSQL_DATABASE=voting
      - MYSQL_USER=voting
      - MYSQL_PASSWORD=voting
    ports:
      - "3306:3306"
    networks:
      - app_net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      retries: 5


  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app_net
  
  app:
    build: .
    env_file:
      - .env.dist
#    command: ["php", "artisan", "migrate", "--force"]
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_net

  
networks:
  app_net: