services:
  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "20000:80"
    depends_on:
      - app
    networks:
      - app_net
  db:
    image: postgres:17.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  
  redis:
    image: redis:8.0-M04-alpine
    ports:
      - "6379:6379"

  app:
    build: .
    env_file:
      - .env
    # logging:
    #   driver: "fluentd"
    #   options:
    #     fluentd-address: "fluentd:24224" 
    #     tag: "go.gin"
    ports:
      - "8080:8080"
    restart: always

  elasticsearch:
    image: elasticsearch:8.16.6
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
  
  kibana:
    image: kibana:8.16.6
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./logs:/var/log/app
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    # depends_on:
    #   - elasticsearch

    

networks:
  app_net: