x-logging:
  &loki
  logging:
    driver: loki
    options:
      loki-url: "http://loki:3100/loki/api/v1/push"
      loki-batch-size: "400"
      loki-retries: "5"


services:
  go-app:
    image: diyorbek001/go-app:latest
    ports:
      - "8080:8080"
    <<: *loki
    networks:
      - app-net

  loki:
    image: grafana/loki:latest    
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - loki:/data/loki
    command: 
      -config.file=/etc/loki/loki-config.yaml
    networks:
      - app-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-net

volumes:
  loki:

networks:
  app-net:
    external: true
    driver: "bridge"