services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - go-app
    networks:
      - app-net

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "5433:5432"
    networks:
      - app-net

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app-net

  go-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: ":8080"
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: appdb
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    networks:
      - app-net

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-net

  loki:
    image: grafana/loki:3.0.0                       # Specifies the Loki Docker image and version.
    container_name: loki                            # Names the container for easier management.
    volumes:
      - ./loki-config.yaml:/mnt/config/loki-config.yaml # Mounts the Loki configuration file.
      - ./data:/tmp
    ports:
      - "3100:3100"                                 # Maps port 3100 on the host to port 3100 in the container.
    command: -config.file=/mnt/config/loki-config.yaml # Runs Loki with the specified configuration file.
    networks:
      - app-net

  promtail:
      image: grafana/promtail:3.0.0                   # Specifies the Promtail Docker image and version.
      container_name: promtail                        # Names the container for easier management.
      volumes:
        - ./promtail-config.yaml:/mnt/config/promtail-config.yaml # Mounts the Promtail configuration file.
        - /var/log:/var/log                           # Mounts the host's log directory.
      depends_on:
        - loki                                       # Ensures Promtail starts after Loki.
      command: -config.file=/mnt/config/promtail-config.yaml
      networks:
        - app-net


  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
