
name: Golang Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug working dir
        run: |
          pwd
          ls -la

      - name: Create Loki data dir with correct permissions
        run: |
          mkdir -p ./data
          chmod -R 777 ./data

      - name: Deploy with Docker Compose
        run: |
          cd ${{ github.workspace }}
          docker compose down
          docker compose up -d --build
